### ISSUE TITLE
Where to find the rest API's

### ISSUE THREAD

**Issue by suchetaswabhav** [Kong/insomnia.rest#23]
Hi,

I want to know where to find the api's like GET/POST/PUT/DELETE code in the source code. I just want to use them. I found the front end. Please help me figure our the backend api's.  Because i want to integrate them in my MEAN application.

P.S.: Or is there a way to embedd insomnia rest client directly in my application.

**Comment by anthonylouisbsb** [comment]
I think you are looking for it https://github.com/getinsomnia/insomnia.rest/blob/31122f42509f6ab4a814ffc9e0387f8518543bcf/src/lib/fetch.js . In this file there are all commands that you said.
