### ISSUE TITLE
Broken AppImage link in the documentation

### ISSUE THREAD

**Issue by maaraanas** [Kong/insomnia.rest#27]
https://support.insomnia.rest/article/23-installation#linux

AppImage link route here
https://github.com/getinsomnia/insomnia/releases/download/v7.0.3/Insomnia.7.0.3.AppImage
![image](https://user-images.githubusercontent.com/23417649/69657607-40ac1100-1083-11ea-84df-5a9fdaeaf7e5.png)

**Correct URL** https://github.com/getinsomnia/insomnia/releases/tag/v7.0.4-beta.3

**Comment by gschier** [comment]
It seems to be working as of now. Note that betas will not be recommended
